# Generated by Django 4.0.2 on 2022-02-22 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_date_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 18, 0, 25, 512633, tzinfo=utc)),
        ),
    ]
